### ISSUE TITLE
After Running the TTL is changed to Auto

### ISSUE THREAD

**Issue by gregor-hh** [L480/cloudflare-dyndns#15]
Hello,

at first thank you very much for the great middleware api!

Only one thing:

I created an A-Record with TTL 1min. After updating the record with the Middleware, the TTL ist changed to auto.

But I want the lowest TTL possible.

Can you edit the code, so the original TTL is read from the record and then also be used for the update of the record?

Regards
Gregor

**Comment by L480** [comment]
Hi Gregor,

Done. The TTL and proxied settings will now remain unchanged during the record update.

Regards,
Nico
