### ISSUE TITLE
Possible to use top domain instead of www. ?

### ISSUE THREAD

**Issue by c0dingnoobi** [L480/cloudflare-dyndns#19]
I am currently trying to setup the update url through FritzBox. 
Kind of unsure what to use for record= when using top domains instead of the predefined www. 
Preview the settings used inside of FritzBox:
URL: ```https://functions.nicoo.org/function/cloudflare-dyndns?token=<pass>&record=****.com&zone=****.com&ipv4=<ipaddr>```
Domainname: ```****.com```
User: admin
Passw: ```<apitoken>```

**Comment by peterchen19** [comment]
same here, want to use my root domain and tried several things for record:
- mydomain.domain
-@
-*
-@.mydomain.domain
-*.mydomain.domain

but no luck

**Comment by Aleklu** [comment]
Same here. Did any of you proceed with this?

**Comment by peterchen19** [comment]
No not exatly, i created a random subdomain (just hit some key on my keybord for an giberish) and uesd this for my dyndns. After that i used a CNAME for my root domain. Not tze best solution but ist works. Still i'm searching to use my root domain directly

**Comment by c0dingnoobi** [comment]
used the same workaround
