### ISSUE TITLE
A / AAAA record does not exist error

### ISSUE THREAD

**Issue by Fi0x** [L480/cloudflare-dyndns#2]
### Problem
I only get a 404 response when I add your settings to my Fritz!Box.
I'm using a Strato domain with cloudflare.
I tried using ipv4 and ipv6, neither worked (ipv4 will probably never work due to my provider)

### Settings
- Strato domain
- cloudflare setup
- A record is shown in cloudflare
- AAAA record is shown in cloudflare
- DynDNS settings in Fritz!Box as you explained

### Screenshots
*Cloudflare*
![image](https://user-images.githubusercontent.com/58072122/139091604-3113914e-d6ce-4bf7-80a7-27cd744616ce.png)

*Strato*
![image](https://user-images.githubusercontent.com/58072122/139017302-e3a48d77-b5f4-4b59-9f4a-595586b6d145.png)

**Comment by gitgudchannel** [comment]
What would I have to specify for `record` if I only want to change my A record? Essentially, I don't want to change the A record for `www.example.com`, but I want to change the A record for `example.com`.
