### ISSUE TITLE
Cloud service

### ISSUE THREAD

**Issue by Joey291** [L480/cloudflare-dyndns#25]
Hey, i was using your free cloud service for my fritzbox. it somehow stopped working. is there any issues or is it my place ?

**Comment by derwolle** [comment]
Same problem here, you're not alone. "DNS record not found" for functions.nicoo.org.

Thx anyway for the free service!

**Comment by Joey291** [comment]
yes thanks for the service. i set this up for a friend of mine. he called me that he cant reach his camera from outside anymore since a few days. now i had to switch, i am hosting this for him now. thankfully docker image for selfhosting is working

**Comment by L480** [comment]
Please use the new url `https://dyndns.nicoo.org/?token=<pass>&record=www&zone=example.com&ipv4=<ipaddr>&ipv6=<ip6addr>`. Please excuse the inconvenience.
