### ISSUE TITLE
How to update a NON WWW A-Record for my domain

### ISSUE THREAD

**Issue by FurkanVG** [L480/cloudflare-dyndns#30]
Hey,
either im very confused, or im very blind, or dumb :) 

I switched the Nameservers for my Domain from Strato.de to Cloudfare. Thats why i fell for this script since this would be the perfect fix for my issue right now. But from my perspective, your tool can only MODIFY a www A-Record?

![image](https://github.com/L480/cloudflare-dyndns/assets/68749298/0b351451-ac46-4d1e-bee7-a913d638893b)

https://dyndns.nicoo.org/?token=XXXXXXXXXXXX&record=www&zone=furrkan.de&ipv4=<ipaddr>

If i use this update line, it can Update the DNS entry for the WWW Record, but i dont want that. I wanna update the record for furrkan.de. I thought i can do it like this:
https://dyndns.nicoo.org/?token=XXXXXXXXXXXX&record=furrkan.de&zone=furrkan.de&ipv4=<ipaddr>
![image](https://github.com/L480/cloudflare-dyndns/assets/68749298/a825c5e1-369a-4428-aace-632bf5c59f76)
But then i get this error.
So either im confused how to update it, or your tool doesnt  support it.
Thanks for helping!

**Comment by L480** [comment]
Check out https://github.com/L480/cloudflare-dyndns/pull/28. Just omit "record" for apex domains.

**Comment by FurkanVG** [comment]
Oh wow, looks like i was dumb. Thanks, it works!
