### ISSUE TITLE
FRITZ!Box gives weird logs, but DynDNS Update still works!

### ISSUE THREAD

**Issue by FurkanVG** [L480/cloudflare-dyndns#31]
Hey,
this is not something actually broken, but its annyoing:

![image](https://github.com/L480/cloudflare-dyndns/assets/68749298/bb4c9321-8220-4fcc-9a4d-3dac7df327b6)

My FRITZ!Box has lots of logs about DynDNS failing, but its not actually failing.
I have confirmed that the DynDNS Update works, just wondering why i get these logs.
Anyone else?

**Comment by FurkanVG** [comment]
Dead?

**Comment by L480** [comment]
What response do you get when making the GET call to the update URL through your browser?

**Comment by FurkanVG** [comment]
I get the output as expected, but when its ran through Fritzbox DynDNS Update system, i get these log errors:

When i ran it manually:

https://dyndns.nicoo.org/?token=XXXXXXXXXXXXXX&zone=furrkan.de&ipv4=XXXXXXXX

![image](https://github.com/L480/cloudflare-dyndns/assets/68749298/4cac25a1-6ff2-4ef0-a5a4-45ae1fbe7922)

When my Fritzbox does it on its own:

https://dyndns.nicoo.org/?token=XXXXXXXXXXXX&zone=furrkan.de&ipv4=<ipaddr>

![image](https://github.com/L480/cloudflare-dyndns/assets/68749298/4c85bbba-4e31-4153-a89c-60c8b1e175f6)

Sadly the Fritz doesnt log more than this general info, or?
Thanks

**Comment by L480** [comment]
AFAIK there are no additional logs on FritzBox. As the update URL returns an HTTP 200 I would suggest opening a support case with AVM.

**Comment by FurkanVG** [comment]
ok ty, closing it!
